# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx_second', models.IntegerField()),
                ('idx_third', models.IntegerField()),
                ('other', models.IntegerField(null=True)),
                ('idx_first', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='example',
            unique_together=set([('idx_first', 'idx_second', 'idx_third')]),
        ),
    ]
