# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='example',
            unique_together=set([]),
        ),
    ]
